name: Deploy Pet Step Server Nodejs Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_DB_PATH: ${{ secrets.MONGO_DB_PATH }}
      MONGO_EXPRESS_PORT: ${{ secrets.MONGO_EXPRESS_PORT }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      JWT_SECRET_ACCESS_TOKEN: ${{ secrets.JWT_SECRET_ACCESS_TOKEN }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      STMP_HOST: ${{ secrets.STMP_HOST }}
      STMP_PORT: ${{ secrets.STMP_PORT }}
      STMP_USER: ${{ secrets.STMP_USER }}
      STMP_PASSWORD: ${{ secrets.STMP_PASSWORD }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PET_STEP_FRONT: ${{ secrets.PET_STEP_FRONT }}
      REAL_TIME_DATABSE: ${{ secrets.REAL_TIME_DATABSE }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/petstep-nodejs-app .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/petstep-nodejs-app:latest

  deploy:
    needs: build
    runs-on: petStepServerRunner
    env:
      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_DB_PATH: ${{ secrets.MONGO_DB_PATH }}
      MONGO_EXPRESS_PORT: ${{ secrets.MONGO_EXPRESS_PORT }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      JWT_SECRET_ACCESS_TOKEN: ${{ secrets.JWT_SECRET_ACCESS_TOKEN }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{AWS_SECRET_ACCESS_KEY}}
      PET_STEP_FRONT: ${{PET_STEP_FRONT}}
      FIREBASE_REAL_TIME_DATABSE: ${{FIREBASE_REAL_TIME_DATABSE}}
      FIREBASE_PROJECT_ID: ${{FIREBASE_PROJECT_ID}}
      FIREBASE_PRIVATE_KEY: ${{FIREBASE_PRIVATE_KEY}}
      FIREBASE_TYPE: ${{FIREBASE_TYPE}}
      FIREBASE_CLIENT_EMAIL: ${{FIREBASE_CLIENT_EMAIL}}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/petstep-nodejs-app:latest

      - name: Start containers with Docker Compose
        run: docker-compose up -d

      - name: Clean up Docker
        run: docker system prune -af
